### ISSUE TITLE
Close prompt

### ISSUE THREAD

**Issue by blainesch** [freeformsystems/cli-input#6]
How do I close the prompt?

I run this:
~~~ javascript
var prompt = require('cli-input');
var ps = prompt({
  infinite: false,
  format: '>>>'
});
ps.on('value', function(value, options, ps) {
  console.log(value[0]);
})
ps.run();
~~~

After the first iteration the process still hangs.

**Comment by freeformsystems** [comment]
I think you are right and proxy the call to readline now, in the registry as `0.1.2`.

Likely get an error if you call it twice ;)

Unfortunately I was in a rush when I wrote this module so far from tidy, however it does appear to work and I am using it happily in various dependencies (usually as infinite style REPL prompts).

**Comment by blainesch** [comment]
:+1:
